# NUMBER OF CLASSES
num_classes: 10

# DATALOADER PARAMS
DATALOADER:
  batch_size: 32
  num_workers: 4

# TRAINING PARAMS
TRAINING:
  num_classes: 10
  epochs: 20
  learning_rate: 0.0001
  patience: 5
  reduce_lr_factor: 0.3
  reduce_lr_patience: 2

MODEL:
  pretrained: true